version: '3.9'

services:
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/dozzle/auth/data:/data"
    ports:
      - 8888:8080
    environment:
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_NO_ANALYTICS: 1
    networks:
      - traefik-net

  db:
    image: postgres:16
    container_name: flectra-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: flectra
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra/postgresql:/var/lib/postgresql/data"
    networks:
      - traefik-net

  flectra:
    image: flectrahq/flectra:3.0
    platform: linux/amd64
    user: flectra
    container_name: flectra
    restart: unless-stopped
    depends_on:
      - db
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=flectra
      - PASSWORD=${DB_PASSWORD}
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra/etc/config:/var/lib/flectra:rw"
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra/etc/addons:/mnt/extra-addons:ro"
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra/etc/logs:/var/log/flectra:rw"
    labels:
      - traefik.enable=true
      - traefik.http.routers.flectra.rule=Host(`finance.bergsoemetals.com`)
      - traefik.http.routers.flectra.entrypoints=websecure
      - traefik.http.routers.flectra.tls=true
      - traefik.http.routers.flectra.tls.certresolver=default-resolver
      - traefik.http.routers.flectra.service=flectra
      - traefik.http.services.flectra.loadbalancer.server.port=7073
      - traefik.http.middlewares.flectra-headers.headers.contentSecurityPolicy=upgrade-insecure-requests
      - traefik.http.middlewares.compress.compress=true
      - traefik.http.routers.flectra.middlewares=flectra-headers,compress
      - traefik.http.routers.flectra_lp.rule=Host(`flectra.bergsoemetals.com`) && PathPrefix(`/longpolling/`)
      - traefik.http.routers.flectra_lp.entrypoints=websecure
      - traefik.http.routers.flectra_lp.tls=true
      - traefik.http.routers.flectra_lp.tls.certresolver=default-resolver
      - traefik.http.routers.flectra_lp.service=flectra_lp
      - traefik.http.services.flectra_lp.loadbalancer.server.port=7072
      - traefik.http.routers.flectra_lp.middlewares=flectra-headers,compress
    ports:
      - 8000:7073  # Expose locally for dev if needed
      - 8001:7072  # If longpolling is configured
    networks:
      - traefik-net
    # command: -d flectra -i base --stop-after-init
    # enable the command line to initialize the database; first time start up only

  db-2.0:
    image: postgres:16
    container_name: flectra-db-2.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: flectra
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra-2.0/postgresql:/var/lib/postgresql/data"
    networks:
      - traefik-net

  flectra-2.0:
    image: flectrahq/flectra:2.0
    platform: linux/amd64
    user: flectra
    container_name: flectra-2.0
    restart: unless-stopped
    depends_on:
      - db-2.0
    tty: true
    # command: -d flectra -i base --stop-after-init  # Comment out after initial setup
    environment:
      - HOST=db-2.0
      - USER=flectra
      - PASSWORD=${DB_PASSWORD}
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra-2.0/etc/config:/var/lib/flectra:rw"
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra-2.0/etc/addons:/mnt/extra-addons:ro"
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra-2.0/etc/logs:/var/log/flectra:rw"
    labels:
      - traefik.enable=true
      - traefik.http.routers.flectra-2.0.rule=Host(`finance2.bergsoemetals.com`)
      - traefik.http.routers.flectra-2.0.entrypoints=websecure
      - traefik.http.routers.flectra-2.0.tls=true
      - traefik.http.routers.flectra-2.0.tls.certresolver=default-resolver
      - traefik.http.routers.flectra-2.0.service=flectra-2.0
      - traefik.http.services.flectra-2.0.loadbalancer.server.port=7073
      - traefik.http.middlewares.flectra-headers.headers.contentSecurityPolicy=upgrade-insecure-requests
      - traefik.http.middlewares.compress.compress=true
      - traefik.http.routers.flectra-2.0.middlewares=flectra-headers,compress
      - traefik.http.routers.flectra_lp-2.0.rule=Host(`flectra2.bergsoemetals.com`) && PathPrefix(`/longpolling/`)
      - traefik.http.routers.flectra_lp-2.0.entrypoints=websecure
      - traefik.http.routers.flectra_lp-2.0.tls=true
      - traefik.http.routers.flectra_lp-2.0.tls.certresolver=default-resolver
      - traefik.http.routers.flectra_lp-2.0.service=flectra_lp-2.0
      - traefik.http.services.flectra_lp-2.0.loadbalancer.server.port=7072
      - traefik.http.routers.flectra_lp-2.0.middlewares=flectra-headers,compress
    ports:
      - 8002:7073  # Different local port to avoid conflict
      - 8003:7072  # Different local port to avoid conflict
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true