version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: "traefik"
    restart: always
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.default-resolver.acme.httpchallenge=true
      - --certificatesresolvers.default-resolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.default-resolver.acme.email=info@mindfulmunchkins.com
      - --certificatesresolvers.default-resolver.acme.storage=/letsencrypt/acme.json
      - --api.dashboard=true
      - --api.insecure=true
      - --accesslog=true
      - --accesslog.filepath=/logs/access.log
      - --metrics.prometheus=true
      - --metrics.prometheus.entryPoint=metrics
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --entrypoints.metrics.address=:8082  # Define the metrics entrypoint
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8082:8082"  # Expose the metrics port
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/traefik/letsencrypt:/letsencrypt"
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/traefik/logs:/logs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-net

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: always
    volumes:
      - ~/mydata/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - ~/mydata/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - traefik-net
      
  mysql:
    image: arm64v8/mysql:8.0
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
      TZ: UTC
    ports:
      - 3306:3306
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/mysql/data/db:/var/lib/mysql"
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/mysql/data/conf:/etc/mysql/conf.d"
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/mysql/log:/var/log/mysql"
    networks:
      - traefik-net

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - traefik-net

volumes:
  redis-data:

networks:
  traefik-net:
    external: true