version: '3.9'

services:
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/dozzle/auth/data:/data"
    ports:
      - 8888:8080
    environment:
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_NO_ANALYTICS: 1
    networks:
      - traefik-net

  db-2.0:
    image: postgres:16
    container_name: flectra-db-2.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: flectra
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra-2.0/postgresql:/var/lib/postgresql/data"
    networks:
      - traefik-net

  flectra-2.0:
    image: flectrahq/flectra:2.0
    platform: linux/amd64
    user: flectra
    container_name: flectra-2.0
    restart: unless-stopped
    depends_on:
      - db-2.0
    tty: true
    command: flectra --http-port=7073 --longpolling-port=7072  # Explicitly set ports to match labels
    environment:
      - HOST=db-2.0
      - USER=flectra
      - PASSWORD=${DB_PASSWORD}
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra-2.0/etc/config:/var/lib/flectra:rw"
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra-2.0/etc/addons:/mnt/extra-addons:ro"
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/flectra-2.0/etc/logs:/var/log/flectra:rw"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.flectra.rule=Host(`finance.bergsoemetals.com`)
      - traefik.http.routers.flectra.entrypoints=websecure
      - traefik.http.routers.flectra.tls=true
      - traefik.http.routers.flectra.tls.certresolver=default-resolver
      - traefik.http.routers.flectra.service=flectra
      - traefik.http.services.flectra.loadbalancer.server.port=7073
      - traefik.http.routers.flectra_lp.rule=Host(`finance.bergsoemetals.com`) && PathPrefix(`/longpolling/`)
      - traefik.http.routers.flectra_lp.entrypoints=websecure
      - traefik.http.routers.flectra_lp.tls=true
      - traefik.http.routers.flectra_lp.tls.certresolver=default-resolver
      - traefik.http.routers.flectra_lp.service=flectra_lp
      - traefik.http.services.flectra_lp.loadbalancer.server.port=7072
    ports:
      - 8002:7073  # Different local port to avoid conflict
      - 8003:7072  # Different local port to avoid conflict
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true